# .github/workflows/deploy-shinyapp.yml

name: Déploiement sur ShinyApps.io

on:
  push:
    branches:
      - main

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Mise en place de R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5'
      
      - name: Installation des dépendances système
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libgdal-dev libudunits2-dev gdal-bin libproj-dev

      - name: Mise en place du cache renv
        uses: r-lib/actions/setup-renv@v2

      - name: Déploiement de l'application
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='${{ secrets.SHINYAPPS_ACCOUNT }}', token='${{ secrets.SHINYAPPS_TOKEN }}', secret='${{ secrets.SHINYAPPS_SECRET }}')"
          Rscript -e "rsconnect::deployApp(forceUpdate = TRUE)"